name: list installed packages

on:
  # allow manually trigger
  workflow_dispatch:

jobs:
  apt:
    runs-on: ubuntu-latest
    steps:
      - run: apt list --installed

  # https://unix.stackexchange.com/a/411473/378105
  dpkg:
    runs-on: ubuntu-latest
    steps:
      - run: dpkg -l
      - run: dpkg -l | grep ^ii
      - run: dpkg -l | grep ^ii | awk '{print $2}'
