name: Run build if check passed

on:
  # allow manually trigger
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      need-build: ${{ steps.check.outputs.need-build }}
    steps:
      - name: Check pass
        id: check
        run: |
          echo "::set-output name=need-build::true"

  build:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.outputs.need-build == 'true' }}
    steps:
      - run: echo start build...
