name: Share variable between jobs/steps using GITHUB_OUTPUT

on:
  # allow manually trigger
  workflow_dispatch:

jobs:
  first:
    runs-on: ubuntu-latest
    outputs:
      message: ${{ steps.set-output.outputs.message }}
    steps:
      - name: Set output
        id: set-output
        run: echo "message=hello world" >> $GITHUB_OUTPUT

  second:
    runs-on: ubuntu-latest
    needs: first
    steps:
      - name: Get output
        run: echo message is ${{ needs.first.outputs.message }}

  shell-variables-in-the-same-job:
    runs-on: ubuntu-latest
    steps:
      - name: Set output
        id: set-output
        run: echo "message=hello world" >> $GITHUB_OUTPUT
      - name: Get output
        run: echo message is ${{ steps.set-output.outputs.message }}
