name: Skip build if check failed

on:
  # allow manually trigger
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      need-build: ${{ steps.check.outputs.need-build }}
    steps:
      - name: Check fail
        id: check
        run: |
          echo "need-build=false" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.outputs.need-build == 'true' }}
    steps:
      - run: echo start build...
